"""phase 1 baseline: users, vendors, stalls, products, food_items

Revision ID: 0001_phase1_initial
Revises:
Create Date: 2026-09-17

Written by hand rather than autogenerated: Phase 1 shipped with an empty
alembic/versions/ directory, so there is no schema to diff against and no
guarantee a database is reachable at build time. Column definitions mirror
app/models/ exactly.

If your database already contains these tables (e.g. created manually),
do NOT run this migration -- stamp it instead:

    alembic stamp 0001_phase1_initial
    alembic upgrade head
"""

import sqlalchemy as sa
from alembic import op

revision = "0001_phase1_initial"
down_revision = None
branch_labels = None
depends_on = None

# Values (not member names) to match models/user.py's values_callable.
# The type itself is created implicitly by the first create_table that
# references it -- calling .create() here as well would emit CREATE TYPE
# twice. It is dropped explicitly in downgrade(), since dropping a table
# does not drop the enum type it used.
user_role_enum = sa.Enum(
    "vendor", "reviewer", "consumer", "admin", name="userrole"
)


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("role", user_role_enum, nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "vendors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("preferred_language", sa.String(), server_default="en"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_vendors_id"), "vendors", ["id"], unique=False)

    op.create_table(
        "stalls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("qr_code_id", sa.String(), nullable=False),
        sa.Column("food_category", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("hygiene_score", sa.Float(), nullable=True),
        sa.Column("is_flagged", sa.Integer(), server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stalls_id"), "stalls", ["id"], unique=False)
    op.create_index(op.f("ix_stalls_name"), "stalls", ["name"], unique=False)
    op.create_index(op.f("ix_stalls_qr_code_id"), "stalls", ["qr_code_id"], unique=True)

    op.create_table(
        "food_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stall_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["stall_id"], ["stalls.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_food_items_id"), "food_items", ["id"], unique=False)
    op.create_index(op.f("ix_food_items_name"), "food_items", ["name"], unique=False)

    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stall_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("ingredients_text", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("explanation", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["stall_id"], ["stalls.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)


def downgrade() -> None:
    op.drop_table("products")
    op.drop_table("food_items")
    op.drop_table("stalls")
    op.drop_table("vendors")
    op.drop_table("users")
    user_role_enum.drop(op.get_bind(), checkfirst=True)
