"""Add auth_provider and provider_id to User

Revision ID: 279dc7bab890
Revises: 8194f498926e
Create Date: 2026-09-18 18:32:17.095028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279dc7bab890'
down_revision: Union[str, None] = '8194f498926e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    auth_provider_enum = sa.Enum('local', 'google', 'digilocker', name='authprovider')
    auth_provider_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('auth_provider', auth_provider_enum, nullable=False, server_default='local'))
    op.add_column('users', sa.Column('provider_id', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
