"""Add AuditLog and AnalyticsAggregate

Revision ID: 8194f498926e
Revises: 983bad9ff3a2
Create Date: 2026-09-18 11:28:40.342124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8194f498926e'
down_revision: Union[str, None] = '983bad9ff3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_stalls', sa.Integer(), nullable=False),
    sa.Column('assessed_stalls', sa.Integer(), nullable=False),
    sa.Column('flagged_stalls', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('scans_performed', sa.Integer(), nullable=False),
    sa.Column('flags_created', sa.Integer(), nullable=False),
    sa.Column('flags_resolved', sa.Integer(), nullable=False),
    sa.Column('checks_performed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_aggregates_date'), 'analytics_aggregates', ['date'], unique=True)
    op.create_index(op.f('ix_analytics_aggregates_id'), 'analytics_aggregates', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analytics_aggregates_id'), table_name='analytics_aggregates')
    op.drop_index(op.f('ix_analytics_aggregates_date'), table_name='analytics_aggregates')
    op.drop_table('analytics_aggregates')
    # ### end Alembic commands ###
