"""consumer reports

Revision ID: 983bad9ff3a2
Revises: 0005_phase5_reviewer
Create Date: 2026-09-18 10:11:40.571150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983bad9ff3a2'
down_revision: Union[str, None] = '0005_phase5_reviewer'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stall_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stall_id'], ['stalls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumer_reports_id'), 'consumer_reports', ['id'], unique=False)
    op.create_index(op.f('ix_consumer_reports_stall_id'), 'consumer_reports', ['stall_id'], unique=False)
    op.drop_index('ix_hygiene_checks_indicators_found_gin', table_name='hygiene_checks', postgresql_using='gin')
    op.drop_index('ix_ingredient_rules_ingredient_id', table_name='ingredient_rules')
    op.drop_index('ix_ingredient_synonyms_ingredient_id', table_name='ingredient_synonyms')
    op.drop_index('ix_product_ingredients_product_id', table_name='product_ingredients')
    op.drop_index('ix_qr_codes_stall_id', table_name='qr_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_qr_codes_stall_id', 'qr_codes', ['stall_id'], unique=False)
    op.create_index('ix_product_ingredients_product_id', 'product_ingredients', ['product_id'], unique=False)
    op.create_index('ix_ingredient_synonyms_ingredient_id', 'ingredient_synonyms', ['ingredient_id'], unique=False)
    op.create_index('ix_ingredient_rules_ingredient_id', 'ingredient_rules', ['ingredient_id'], unique=False)
    op.create_index('ix_hygiene_checks_indicators_found_gin', 'hygiene_checks', ['indicators_found'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_consumer_reports_stall_id'), table_name='consumer_reports')
    op.drop_index(op.f('ix_consumer_reports_id'), table_name='consumer_reports')
    op.drop_table('consumer_reports')
    # ### end Alembic commands ###
